float64 resolution      # Map resolution in meters/pixel.

geometry_msgs/Point origin            # The coordinates of the map's origin.

int32 widthInPixels       # Map's width in pixels.

int32 heightInPixels      # Map's height in pixels.

float64 occupiedThresh  # Threshold for occupancy probability to be considered compeletely occupied.

float64 freeThresh      # Threshold for occupancy probability to be considered compeletely free.