string parameter      # Full name of optional parameter, e.g. “order.nodes.nodePosition.allowedDeviationTheta”. 

string support        # Type of support for the optional parameter, the following values are possible: 
                      # SUPPORTED: optional parameter is supported like specified.
                      # REQUIRED: optional parameter is required for proper AGV-operation. 

string description    # Free-form text: description of optional parameter, e.g.: 
                      # Reason, why the optional parameter ‘direction’ is necessary for this AGV-type and which values it can contain. 
                      # The parameter ‘nodeMarker’ must contain unsigned interger-numbers only. 
                      # NURBS-Support is limited to straight lines and circle segments. 