float64 speedMin          # [m/s] Minimal controlled continuous speed of the AGV

float64 speedMax          # [m/s] Maximum speed of the AGV

float64 accelerationMax   # [m/s²] Maximum acceleration with maximum load

float64 decelerationMax   # [m/s²] Maximum deceleration with maximum load

float64 heightMin         # [m] Minimum height of AGV

float64 heightMax         # [m] Maximum height of AGV

float64 width             # [m] Width of AGV

float64 length            # [m] Length of AGV