float32 minOrderInterval        # [s], Minimum interval sending order messages to the AGV. 

float32 minStateInterval        # [s], Minimum interval for sending statemessages. 

float32 defaultStateInterval    # [s], Default interval for sending statemessages, if not defined, the default value from the main document is used. 

float32 visualizationInterval   # [s], Default interval for sending messages on visualization topic. 